# Generated by Django 4.2.3 on 2023-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='password',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
    ]
