# Generated by Django 4.2.3 on 2023-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctors_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='username',
            field=models.CharField(default='username', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
