# Generated by Django 4.2.3 on 2023-07-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_doctors_username_alter_doctors_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
